apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: psych-api
  namespace: psych
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: psych.internal
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: psych-api
                port:
                  number: 80
