name: Sync backend â†’ main & Build + Deploy Docker

on:
  push:
    branches:
      - backend

jobs:
  ssh-test:
    runs-on: ubuntu-latest

    steps:
      - name: ðŸ§ª Debug SERVER_IP
        run: |
              if [ -z "${{ secrets.SERVER_HOST }}" ]; then
              echo "âŒ SERVER_IP is EMPTY or NOT SET"
              else
              echo "âœ… SERVER_IP is set: ${{ secrets.SERVER_HOST }}"
              fi

      - name: ðŸ” Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: ðŸ§ª Test SSH connection
        run: |
          ssh -i ~/.ssh/id_ed25519 \
            -o BatchMode=yes \
            -o StrictHostKeyChecking=yes \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} \
            "echo CONNECTED && whoami && hostname"
